--ClothesBox Redux
--https://steamcommunity.com/sharedfiles/filedetails/?id=2847911733
if getActivatedMods():contains("ClothesBoxRedux") then
--Clothing - Bag
GaistUtils.doParam("Base.CBX_Ras_army","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Ras_ohota","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_1_L","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_1_R","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_1M_L","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_1M_R","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_2_L","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_2_R","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_HR","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_ANAT","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_3_L","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_3_R","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_4_L","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_4_R","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_5_L","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_5_R","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_6","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_7_L","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_7_R","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_8P","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_Sumk_8","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_RUKSAK1","DisplayCategory","ClothB")
GaistUtils.doParam("Base.CBX_RUKSAK2","DisplayCategory","ClothB")
--Clothing - Head
GaistUtils.doParam("Base.CBX_CAPARM_1","DisplayCategory","ClothH")
GaistUtils.doParam("Base.CBX_CAPARM_2","DisplayCategory","ClothH")
GaistUtils.doParam("Base.CBX_CAPARM_3","DisplayCategory","ClothH")
GaistUtils.doParam("Base.CBX_CAPARM_4","DisplayCategory","ClothH")
--Clothing - Accessory
GaistUtils.doParam("Base.CBX_Glasses_1","DisplayCategory","ClothA")
GaistUtils.doParam("Base.CBX_Glasses_2","DisplayCategory","ClothA")
GaistUtils.doParam("Base.CBX_Glasses_3","DisplayCategory","ClothA")
GaistUtils.doParam("Base.CBX_OHI_1","DisplayCategory","ClothA")
GaistUtils.doParam("Base.CBX_OHI_2","DisplayCategory","ClothA")
GaistUtils.doParam("Base.CBX_OHI_3","DisplayCategory","ClothA")
GaistUtils.doParam("Base.CBX_OHI_4","DisplayCategory","ClothA")
GaistUtils.doParam("Base.CBX_OHI_5","DisplayCategory","ClothA")
GaistUtils.doParam("Base.CBX_OHI_6","DisplayCategory","ClothA")
GaistUtils.doParam("Base.CBX_OHI_7","DisplayCategory","ClothA")
GaistUtils.doParam("Base.CBX_OHI_8","DisplayCategory","ClothA")
--Clothing - Suits
GaistUtils.doParam("Base.CBX_Waterproof","DisplayCategory","ClothS")
GaistUtils.doParam("Base.CBX_Kurtk_3","DisplayCategory","ClothS")
GaistUtils.doParam("Base.CBX_KOMB","DisplayCategory","ClothS")
--Clothing - Torso (Outerwear)
GaistUtils.doParam("Base.CBX_Bomber","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_1","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_2","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_4","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Vest_ForemanOPEN","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Vest_HighVizOPEN","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Vest_Hunting_CamoGreenOPEN","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Vest_Hunting_CamoOPEN","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Vest_Hunting_GreyOPEN","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Vest_Hunting_OrangeOPEN","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_KOS","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_SP1OP","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_SP1","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_5OP","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_5","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_6OP","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_6","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_RUBOP","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_RUB","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_7OP","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_7","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_7_1OP","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_7_1","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_8OP","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_8","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_9OP","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_9","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_10OP","DisplayCategory","ClothTO")
GaistUtils.doParam("Base.CBX_Kurtk_10","DisplayCategory","ClothTO")
--Clothing - Torso
GaistUtils.doParam("Base.CBX_CropTop","DisplayCategory","ClothT")
GaistUtils.doParam("Base.CBX_CropTop_White","DisplayCategory","ClothT")
GaistUtils.doParam("Base.CBX_KOF1","DisplayCategory","ClothT")
GaistUtils.doParam("Base.CBX_KOF2","DisplayCategory","ClothT")
--Clothing - Torso (Underwear)
GaistUtils.doParam("Base.CBX_kupalnuk","DisplayCategory","ClothTU")
GaistUtils.doParam("Base.CBX_LIF1","DisplayCategory","ClothTU")
GaistUtils.doParam("Base.CBX_LIF1_1","DisplayCategory","ClothTU")
GaistUtils.doParam("Base.CBX_LIF2","DisplayCategory","ClothTU")
GaistUtils.doParam("Base.CBX_LIF3","DisplayCategory","ClothTU")
--Clothing - Underwear
GaistUtils.doParam("Base.CBX_PAN_2","DisplayCategory","ClothU")
GaistUtils.doParam("Base.CBX_PAN_3","DisplayCategory","ClothU")
GaistUtils.doParam("Base.CBX_PAN_4","DisplayCategory","ClothU")
GaistUtils.doParam("Base.CBX_SK1","DisplayCategory","ClothU")
GaistUtils.doParam("Base.CBX_PAN_5","DisplayCategory","ClothU")
GaistUtils.doParam("Base.CBX_PAN_6","DisplayCategory","ClothU")
GaistUtils.doParam("Base.CBX_PAN_7","DisplayCategory","ClothU")
--Clothing - Legs
GaistUtils.doParam("Base.CBX_Trousers_Worker","DisplayCategory","ClothL")
GaistUtils.doParam("Base.CBX_SP2","DisplayCategory","ClothL")
GaistUtils.doParam("Base.CBX_PAN","DisplayCategory","ClothL")
GaistUtils.doParam("Base.CBX_ST2","DisplayCategory","ClothL")
GaistUtils.doParam("Base.CBX_ST3","DisplayCategory","ClothL")
GaistUtils.doParam("Base.CBX_ST4","DisplayCategory","ClothL")
GaistUtils.doParam("Base.CBX_SHO1","DisplayCategory","ClothL")
GaistUtils.doParam("Base.CBX_ST5","DisplayCategory","ClothL")
--Clothing - Footwear
GaistUtils.doParam("Base.CBX_BOOT_1","DisplayCategory","ClothF")
end