--[CJ] Firearms | Lore-friendly vanilla expansion
--https://steamcommunity.com/sharedfiles/filedetails/?id=2874163136
if getActivatedMods():contains("CaptainJuezo1") then
--Ammunition
GaistUtils.doParam("Base.357Magnum","DisplayCategory","Ammo");
GaistUtils.doParam("Base.357MagnumBox","DisplayCategory","Ammo");
GaistUtils.doParam("Base.762NATO","DisplayCategory","Ammo");
GaistUtils.doParam("Base.762NATOBox","DisplayCategory","Ammo");
--Tool
GaistUtils.doParam("Base.OpenCJGCK","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJGCK","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJWD40","DisplayCategory","Tool");
GaistUtils.doParam("Base.GUNOIL1","DisplayCategory","Tool");
GaistUtils.doParam("Base.GUNOIL2","DisplayCategory","Tool");
--Weapon - Magazine
GaistUtils.doParam("Base.MagAA12","DisplayCategory","WepAmmoMag");
GaistUtils.doParam("Base.MagSAP6","DisplayCategory","WepAmmoMag");
GaistUtils.doParam("Base.MagBerettaM9","DisplayCategory","WepAmmoMag");
GaistUtils.doParam("Base.MagGlock17","DisplayCategory","WepAmmoMag");
GaistUtils.doParam("Base.MagColt1911","DisplayCategory","WepAmmoMag");
GaistUtils.doParam("Base.MagP226","DisplayCategory","WepAmmoMag");
GaistUtils.doParam("Base.MagAUGA9MM","DisplayCategory","WepAmmoMag");
GaistUtils.doParam("Base.MagM1A","DisplayCategory","WepAmmoMag");
GaistUtils.doParam("Base.MagM60","DisplayCategory","WepAmmoMag");
GaistUtils.doParam("Base.MagM249","DisplayCategory","WepAmmoMag");
--Weapon - Ranged
GaistUtils.doParam("Base.AUGA9MM","DisplayCategory","WepRange");
GaistUtils.doParam("Base.Striker","DisplayCategory","WepRange");
GaistUtils.doParam("Base.SAP6","DisplayCategory","WepRange");
GaistUtils.doParam("Base.Colt1911","DisplayCategory","WepRange");
GaistUtils.doParam("Base.Spas12","DisplayCategory","WepRange");
GaistUtils.doParam("Base.P226","DisplayCategory","WepRange");
GaistUtils.doParam("Base.M1A","DisplayCategory","WepRange");
GaistUtils.doParam("Base.M249","DisplayCategory","WepRange");
GaistUtils.doParam("Base.M60","DisplayCategory","WepRange");
GaistUtils.doParam("Base.M40","DisplayCategory","WepRange");
GaistUtils.doParam("Base.Glock17","DisplayCategory","WepRange");
GaistUtils.doParam("Base.M870","DisplayCategory","WepRange");
GaistUtils.doParam("Base.BerettaM9","DisplayCategory","WepRange");
GaistUtils.doParam("Base.AA12","DisplayCategory","WepRange");
GaistUtils.doParam("Base.ColtPython","DisplayCategory","WepRange");
end

--[CJ] Items | More cigarettes
--https://steamcommunity.com/sharedfiles/filedetails/?id=2879658854
if getActivatedMods():contains("CaptainJuezo2") then
--Drugs
GaistUtils.doParam("Base.U_PCigarrete_Blue","DisplayCategory","Drugs");
GaistUtils.doParam("Base.U_PCigarrete_Deluxe","DisplayCategory","Drugs");
GaistUtils.doParam("Base.U_PCigarrete_Special","DisplayCategory","Drugs");
GaistUtils.doParam("Base.U_PCigarrete_Menthol","DisplayCategory","Drugs");
GaistUtils.doParam("Base.U_PCigarrete_Vanilla","DisplayCategory","Drugs");
GaistUtils.doParam("Base.U_PCigarrete_Strawberry","DisplayCategory","Drugs");
GaistUtils.doParam("Base.U_PCigarrete_Cherry","DisplayCategory","Drugs");
GaistUtils.doParam("Base.U_PCigarrete_Chocolate","DisplayCategory","Drugs");
GaistUtils.doParam("Base.C_PCigs_Blue","DisplayCategory","Drugs");
GaistUtils.doParam("Base.C_PCigs_Deluxe","DisplayCategory","Drugs");
GaistUtils.doParam("Base.C_PCigs_Special","DisplayCategory","Drugs");
GaistUtils.doParam("Base.C_PCigs_Menthol","DisplayCategory","Drugs");
GaistUtils.doParam("Base.C_PCigs_Vanilla","DisplayCategory","Drugs");
GaistUtils.doParam("Base.C_PCigs_Strawberry","DisplayCategory","Drugs");
GaistUtils.doParam("Base.C_PCigs_Cherry","DisplayCategory","Drugs");
GaistUtils.doParam("Base.C_PCigs_Chocolate","DisplayCategory","Drugs");
GaistUtils.doParam("Base.UC_PCigs_Blue","DisplayCategory","Drugs");
GaistUtils.doParam("Base.UC_PCigs_Deluxe","DisplayCategory","Drugs");
GaistUtils.doParam("Base.UC_PCigs_Special","DisplayCategory","Drugs");
GaistUtils.doParam("Base.UC_PCigs_Menthol","DisplayCategory","Drugs");
GaistUtils.doParam("Base.UC_PCigs_Vanilla","DisplayCategory","Drugs");
GaistUtils.doParam("Base.UC_PCigs_Strawberry","DisplayCategory","Drugs");
GaistUtils.doParam("Base.UC_PCigs_Cherry","DisplayCategory","Drugs");
GaistUtils.doParam("Base.UC_PCigs_Chocolate","DisplayCategory","Drugs");
GaistUtils.doParam("Base.UO_PCigs_Blue","DisplayCategory","Drugs");
GaistUtils.doParam("Base.UO_PCigs_Deluxe","DisplayCategory","Drugs");
GaistUtils.doParam("Base.UO_PCigs_Special","DisplayCategory","Drugs");
GaistUtils.doParam("Base.UO_PCigs_Menthol","DisplayCategory","Drugs");
GaistUtils.doParam("Base.UO_PCigs_Vanilla","DisplayCategory","Drugs");
GaistUtils.doParam("Base.UO_PCigs_Strawberry","DisplayCategory","Drugs");
GaistUtils.doParam("Base.UO_PCigs_Cherry","DisplayCategory","Drugs");
GaistUtils.doParam("Base.UO_PCigs_Chocolate","DisplayCategory","Drugs");
--Tool
GaistUtils.doParam("Base.CJLighterBase","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter1","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter2","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter3","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter4","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter5","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter6","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter7","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter8","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter9","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter10","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter11","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter12","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter13","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter14","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter15","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter16","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter17","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter18","DisplayCategory","Tool");
GaistUtils.doParam("Base.CJLighter19","DisplayCategory","Tool");
end