--Small Town Responders (Main)
--https://steamcommunity.com/sharedfiles/filedetails/?id=2623855083
if getActivatedMods():contains("STR") then
--Clothing - Accessory
GaistUtils.doParam("STR.Chest_Walkie","DisplayCategory","ClothA");
--Clothing - Bag
GaistUtils.doParam("STR.Bag_Satchel_USPS","DisplayCategory","ClothB");
--Clothing - Head
GaistUtils.doParam("STR.Hat_Police_Muldraugh","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_Police_Meade","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_Police_WestPoint","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_Police_Riverside","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_Police_Rosewood","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_Police_Louisville","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_Police_JeffersonPD","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_Police_JeffersonSD","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_PoliceKSP","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_FederalRanger","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_StateLawRanger","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_StateRanger","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_BaseballCap_DOC_Meade","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_BaseballCap_DOC_Meade_Reverse","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_BaseballCap_DOC_Jefferson","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_BaseballCap_DOC_Jefferson_Reverse","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_BaseballCap_EMS_Meade","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_BaseballCap_EMS_Meade_Reverse","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_BaseballCap_EMS_Jefferson","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_BaseballCap_EMS_Jefferson_Reverse","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_BaseballCap_EMS_Louisville","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_BaseballCap_EMS_Louisville_Reverse","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_BaseballCap_USPS","DisplayCategory","ClothH");
GaistUtils.doParam("STR.Hat_BaseballCap_USPS_Reverse","DisplayCategory","ClothH");
--Clothing - Helmet
GaistUtils.doParam("STR.Hat_Fireman_Meade_Black","DisplayCategory","ClothHelm");
GaistUtils.doParam("STR.Hat_Fireman_Meade_Red","DisplayCategory","ClothHelm");
GaistUtils.doParam("STR.Hat_Fireman_Meade_Yellow","DisplayCategory","ClothHelm");
GaistUtils.doParam("STR.Hat_Fireman_Rosewood_Black","DisplayCategory","ClothHelm");
GaistUtils.doParam("STR.Hat_Fireman_Rosewood_Red","DisplayCategory","ClothHelm");
GaistUtils.doParam("STR.Hat_Fireman_Rosewood_Yellow","DisplayCategory","ClothHelm");
GaistUtils.doParam("STR.Hat_Fireman_Louisville_Black","DisplayCategory","ClothHelm");
GaistUtils.doParam("STR.Hat_Fireman_Louisville_Red","DisplayCategory","ClothHelm");
GaistUtils.doParam("STR.Hat_Fireman_Louisville_Yellow","DisplayCategory","ClothHelm");
--Clothing - Legs
GaistUtils.doParam("STR.Trousers_Police_Muldraugh","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Police_Meade","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Police_WestPoint","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Police_Riverside","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Police_Rosewood","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Police_Louisville","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Police_JeffersonPD","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Police_JeffersonSD","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_PoliceKSP_Summer","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_PoliceKSP_Winter","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_FederalRanger","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_StateLawRanger","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_StateRanger","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_DOC_Meade","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_DOC_Jefferson","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_EMS_Meade","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_EMS_Jefferson","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_EMS_Louisville","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Fireman_Meade_Black","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Fireman_Meade_Khaki","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Fireman_Rosewood_Black","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Fireman_Rosewood_Khaki","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Fireman_Louisville_Black","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Fireman_Louisville_Khaki","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_USPS","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Shorts_USPS","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Shorts_ShortUSPS","DisplayCategory","ClothL");
--Clothing - Neck
GaistUtils.doParam("STR.Tie_Full_KSP","DisplayCategory","ClothN");
--Clothing - Suit
GaistUtils.doParam("STR.Boilersuit_MeadeGenPopPrisoner","DisplayCategory","ClothS");
GaistUtils.doParam("STR.Boilersuit_MeadeLowRiskPrisoner","DisplayCategory","ClothS");
GaistUtils.doParam("STR.Boilersuit_MeadeMaxPrisoner","DisplayCategory","ClothS");
GaistUtils.doParam("STR.Boilersuit_JeffersonPrisoner","DisplayCategory","ClothS");
GaistUtils.doParam("STR.Judge_Robe","DisplayCategory","ClothS");
--Clothing - Torso
GaistUtils.doParam("STR.Shirt_Police_Muldraugh","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Police_Muldraugh","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_Police_Meade","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Police_Meade","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_Police_WestPoint","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Police_WestPoint","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_Police_Riverside","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Police_Riverside","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_Police_Rosewood","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Police_Rosewood","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_Police_Louisville","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Police_Louisville","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_Police_JeffersonPD","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Police_JeffersonPD","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_Police_JeffersonSD","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Police_JeffersonSD","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_PoliceKSP","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_PoliceKSP","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_Federal_Ranger","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Federal_Ranger","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_State_LawRanger","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_State_LawRanger","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_State_Ranger","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_State_Ranger","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_DOC_Meade","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_DOC_Meade","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_DOC_Jefferson","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_DOC_Jefferson","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_EMS_Meade","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_EMS_Meade","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_EMS_Jefferson","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_EMS_Jefferson","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_EMS_Louisville","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_EMS_Louisville","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Profession_FiremanBlue_Meade","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Profession_FiremanRed_Meade","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Profession_FiremanRed_Meade02","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Profession_FiremanWhite_Meade","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Profession_FiremanBlue_Rosewood","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Profession_FiremanRed_Rosewood","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Profession_FiremanRed_Rosewood02","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Profession_FiremanWhite_Rosewood","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Profession_FiremanBlue_Louisville","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Profession_FiremanRed_Louisville","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Profession_FiremanRed_Louisville02","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_Profession_FiremanWhite_Louisville","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_USPS","DisplayCategory","ClothT");
GaistUtils.doParam("STR.TShirt_USPS","DisplayCategory","ClothT");
--Clothing - Torso (Armor)
GaistUtils.doParam("STR.Vest_BulletPolice_Meade","DisplayCategory","ClothTA");
--Clothing - Torso (Outerwear)
GaistUtils.doParam("STR.Jacket_Police_Muldraugh","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Police_Meade","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Police_WestPoint","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Police_Riverside","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Police_Rosewood","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Police_Louisville","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Police_JeffersonPD","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Police_JeffersonSD","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_PoliceKSP","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Federal_Ranger","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_State_LawRanger","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_State_Ranger","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_DOC_Meade","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_DOC_Jefferson","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_EMS_Meade","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_EMS_Jefferson","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_EMS_Louisville","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Fireman_Meade_Black","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Fireman_Meade_Khaki","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Fireman_Rosewood_Black","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Fireman_Rosewood_Khaki","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Fireman_Louisville_Black","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Fireman_Louisville_Khaki","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_USPS","DisplayCategory","ClothTO");
--Clothing - Waist
GaistUtils.doParam("STR.Belt_PoliceDuty","DisplayCategory","ClothWaist");
end
if getActivatedMods():contains("STSRJ") then
--Clothing - Legs
GaistUtils.doParam("STR.Trousers_Police_MuldraughTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Police_MeadeTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Police_WestPointTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Police_RiversideTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Police_RosewoodTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Police_LouisvilleTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Police_JeffersonPDTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Police_JeffersonSDTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_PoliceKSP_SummerTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_PoliceKSP_WinterTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_FederalRangerTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_StateLawRangerTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_StateRangerTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_DOC_MeadeTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_DOC_JeffersonTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_EMS_MeadeTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_EMS_JeffersonTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_EMS_LouisvilleTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Fireman_Meade_BlackTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Fireman_Meade_KhakiTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Fireman_Rosewood_BlackTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Fireman_Rosewood_KhakiTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Fireman_Louisville_BlackTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_Fireman_Louisville_KhakiTUCK","DisplayCategory","ClothL");
GaistUtils.doParam("STR.Trousers_USPSTUCK","DisplayCategory","ClothL");
--Clothing - Suit
GaistUtils.doParam("STR.Boilersuit_MeadeGenPopPrisonerOPEN","DisplayCategory","ClothS");
GaistUtils.doParam("STR.Boilersuit_MeadeLowRiskPrisonerOPEN","DisplayCategory","ClothS");
GaistUtils.doParam("STR.Boilersuit_MeadeMaxPrisonerOPEN","DisplayCategory","ClothS");
GaistUtils.doParam("STR.Boilersuit_JeffersonPrisonerOPEN","DisplayCategory","ClothS");
--Clothing - Torso
GaistUtils.doParam("STR.Shirt_Police_MuldraughROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_Police_MeadeROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_Police_WestPointROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_Police_RiversideROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_Police_RosewoodROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_Police_LouisvilleROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_Police_JeffersonPDROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_Police_JeffersonSDROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_PoliceKSPROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_Federal_RangerROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_State_LawRangerROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_State_RangerROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_DOC_MeadeROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_DOC_JeffersonROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_EMS_MeadeROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_EMS_JeffersonROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_EMS_LouisvilleROLL","DisplayCategory","ClothT");
GaistUtils.doParam("STR.Shirt_USPSROLL","DisplayCategory","ClothT");
--Clothing - Torso (Outerwear)
GaistUtils.doParam("STR.Jacket_Police_MuldraughOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Police_MeadeOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Police_WestPointOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Police_RiversideOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Police_RosewoodOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Police_LouisvilleOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Police_JeffersonPDOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Police_JeffersonSDOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_PoliceKSPOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Federal_RangerOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_State_LawRangerOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_State_RangerOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_DOC_MeadeOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_DOC_JeffersonOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_EMS_MeadeOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_EMS_JeffersonOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_EMS_LouisvilleOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Fireman_Meade_BlackOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Fireman_Meade_KhakiOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Fireman_Rosewood_BlackOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Fireman_Rosewood_KhakiOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Fireman_Louisville_BlackOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_Fireman_Louisville_KhakiOPEN","DisplayCategory","ClothTO");
GaistUtils.doParam("STR.Jacket_USPSOPEN","DisplayCategory","ClothTO");
end
--RavenCreek Police Department (Overdue Update)
--https://steamcommunity.com/sharedfiles/filedetails/?id=2599486479
if getActivatedMods():contains("RavenCreekPDClothes") then
GaistUtils.doParam("RavenCreekPDClothes.Hat_Police_RavenCreek","DisplayCategory","ClothH");
GaistUtils.doParam("RavenCreekPDClothes.Trousers_Police_RavenCreek","DisplayCategory","ClothL");
GaistUtils.doParam("RavenCreekPDClothes.Shirt_Police_RavenCreek","DisplayCategory","ClothT");
GaistUtils.doParam("RavenCreekPDClothes.TShirt_Police_RavenCreek","DisplayCategory","ClothT");
GaistUtils.doParam("RavenCreekPDClothes.Jacket_Police_RavenCreek","DisplayCategory","ClothTO");
end