--APOCALYPSE MACHINES I
--https://steamcommunity.com/sharedfiles/filedetails/?id=2634753578
--Just in case we belatedly discover there -are- new components here.
--if getActivatedMods():contains("Apocalypse Machines I") then
--end

--APOCALYPSE MACHINES 2 WHEELZ
--https://steamcommunity.com/sharedfiles/filedetails/?id=2638496761
if getActivatedMods():contains("Apocalypse Machines 2 WheelZ")
or getActivatedMods():contains("AM2WModOptions") then
GaistUtils.doParam("Base.OldATVTire","DisplayCategory","MechTire")
GaistUtils.doParam("Base.NormalATVTire","DisplayCategory","MechTire")
GaistUtils.doParam("Base.ModernATVTire","DisplayCategory","MechTire")
GaistUtils.doParam("Base.ATVHood","DisplayCategory","MechHood")
GaistUtils.doParam("Base.CartWindshield","DisplayCategory","MechG")
GaistUtils.doParam("Base.OldCartTire","DisplayCategory","MechTire")
GaistUtils.doParam("Base.NormalCartTire","DisplayCategory","MechTire")
GaistUtils.doParam("Base.ModernCartTire","DisplayCategory","MechTire")
GaistUtils.doParam("Base.OldCartBrake","DisplayCategory","MechB")
GaistUtils.doParam("Base.NormalCartBrake","DisplayCategory","MechB")
GaistUtils.doParam("Base.ModernCartBrake","DisplayCategory","MechB")
GaistUtils.doParam("Base.NormalCartSuspension","DisplayCategory","MechS")
GaistUtils.doParam("Base.ModernCartSuspension","DisplayCategory","MechS")
GaistUtils.doParam("Base.OldCartMuffler","DisplayCategory","MechM")
GaistUtils.doParam("Base.NormalCartMuffler","DisplayCategory","MechM")
GaistUtils.doParam("Base.ModernCartMuffler","DisplayCategory","MechM")
GaistUtils.doParam("Base.SmallTrunk5","DisplayCategory","MechTrunk")
GaistUtils.doParam("Base.NormalTrunk5","DisplayCategory","MechTrunk")
GaistUtils.doParam("Base.BigTrunk5","DisplayCategory","MechTrunk")
GaistUtils.doParam("Base.SmallSaddlebags5","DisplayCategory","MechStor")
GaistUtils.doParam("Base.TrunkDoor5","DisplayCategory","MechTrunk")
GaistUtils.doParam("Base.GloveBox5","DisplayCategory","MechGB")
GaistUtils.doParam("Base.OldScooterTire","DisplayCategory","MechTire")
GaistUtils.doParam("Base.NormalScooterTire","DisplayCategory","MechTire")
GaistUtils.doParam("Base.ModernScooterTire","DisplayCategory","MechTire")
GaistUtils.doParam("Base.OldScooterBrake","DisplayCategory","MechB")
GaistUtils.doParam("Base.NormalScooterBrake","DisplayCategory","MechB")
GaistUtils.doParam("Base.ModernScooterBrake","DisplayCategory","MechB")
GaistUtils.doParam("Base.NormalScooterSuspension","DisplayCategory","MechS")
GaistUtils.doParam("Base.ModernScooterSuspension","DisplayCategory","MechS")
GaistUtils.doParam("Base.OldScooterMuffler","DisplayCategory","MechM")
GaistUtils.doParam("Base.NormalScooterMuffler","DisplayCategory","MechM")
GaistUtils.doParam("Base.ModernScooterMuffler","DisplayCategory","MechM")
GaistUtils.doParam("filcher.SmallTrunk","DisplayCategory","MechTrunk")
GaistUtils.doParam("filcher.OldCycleTire","DisplayCategory","MechTire")
GaistUtils.doParam("filcher.NormalCycleTire","DisplayCategory","MechTire")
GaistUtils.doParam("filcher.ModernCycleTire","DisplayCategory","MechTire")
GaistUtils.doParam("filcher.OldCycleBrake","DisplayCategory","MechB")
GaistUtils.doParam("filcher.NormalCycleBrake","DisplayCategory","MechB")
GaistUtils.doParam("filcher.ModernCycleBrake","DisplayCategory","MechB")
GaistUtils.doParam("filcher.NormalCycleSuspension","DisplayCategory","MechS")
GaistUtils.doParam("filcher.ModernCycleSuspension","DisplayCategory","MechS")
GaistUtils.doParam("filcher.SmallCycleGasTank","DisplayCategory","MechGT")
GaistUtils.doParam("filcher.CycleGasTank","DisplayCategory","MechGT")
GaistUtils.doParam("filcher.CycleBattery","DisplayCategory","MechBat")
GaistUtils.doParam("filcher.CycleHood","DisplayCategory","MechHood")
GaistUtils.doParam("filcher.CycleSeat","DisplayCategory","MechSeat")
GaistUtils.doParam("filcher.CycleSeatSidecar","DisplayCategory","MechSeat")
GaistUtils.doParam("filcher.OldCycleMuffler","DisplayCategory","MechM")
GaistUtils.doParam("filcher.NormalCycleMuffler","DisplayCategory","MechM")
GaistUtils.doParam("filcher.ModernCycleMuffler","DisplayCategory","MechM")
GaistUtils.doParam("filcher.SFMechanicMag4","DisplayCategory","LitR")
end