local distributionTable = VehicleDistributions[1]

distributionTable["89diplomat"] = distributionTable["CarNormal"]
distributionTable["89diplomattaxi1"] = distributionTable["CarTaxi"]
distributionTable["89diplomattaxi2"] = distributionTable["CarTaxi"]
distributionTable["89furytaxi1"] = distributionTable["CarTaxi"]
distributionTable["89furytaxi2"] = distributionTable["CarTaxi"]
distributionTable["90caprice"] = distributionTable["CarNormal"]
distributionTable["90capricetaxi1"] = distributionTable["CarTaxi"]
distributionTable["90capricetaxi2"] = distributionTable["CarTaxi"]
distributionTable["90crownvictoria"] = distributionTable["CarNormal"]
distributionTable["90crownvictoriataxi1"] = distributionTable["CarTaxi"]
distributionTable["90crownvictoriataxi2"] = distributionTable["CarTaxi"]
distributionTable["92crownvictoria"] = distributionTable["CarNormal"]
distributionTable["92crownvictoriataxi1"] = distributionTable["CarTaxi"]
distributionTable["92crownvictoriataxi2"] = distributionTable["CarTaxi"]
distributionTable["92crownvictoriataxi3"] = distributionTable["CarTaxi"]
distributionTable["93aurora"] = distributionTable["CarNormal"]
distributionTable["93crownvictoria"] = distributionTable["CarNormal"]
distributionTable["93crownvictoriataxi1"] = distributionTable["CarTaxi"]
distributionTable["93crownvictoriataxi2"] = distributionTable["CarTaxi"]
distributionTable["93crownvictoriataxi3"] = distributionTable["CarTaxi"]
distributionTable["91oldsmobilecustomcrusier"] = distributionTable["CarStationWagon"]
distributionTable["91buickroadmaster"] = distributionTable["CarNormal"]
distributionTable["91caprice"] = distributionTable["CarNormal"]
distributionTable["93capricewagon"] = distributionTable["CarStationWagon"]
distributionTable["919c1taxi1"] = distributionTable["CarTaxi"]
distributionTable["919c1taxi2"] = distributionTable["CarTaxi"]
distributionTable["93capriceclassic"] = distributionTable["CarNormal"]
distributionTable["93capriceLTZ"] = distributionTable["CarNormal"]
distributionTable["939c1taxi1"] = distributionTable["CarTaxi"]
distributionTable["939c1taxi2"] = distributionTable["CarTaxi"]
distributionTable["93capricetaxi1"] = distributionTable["CarTaxi"]
distributionTable["93capricetaxi2"] = distributionTable["CarTaxi"]
distributionTable["93capricetaxi3"] = distributionTable["CarTaxi"]
distributionTable["91dynasty"] = distributionTable["CarNormal"]
distributionTable["92concord"] = distributionTable["CarNormal"]
distributionTable["93lhs"] = distributionTable["CarNormal"]
distributionTable["93lhstaxi"] = distributionTable["CarTaxi"]
distributionTable["93continental"] = distributionTable["CarNormal"]
distributionTable["92concord"] = distributionTable["CarNormal"]
distributionTable["92premiersts"] = distributionTable["CarNormal"]
distributionTable["92grandmarquis"] = distributionTable["CarNormal"]
distributionTable["92grandmarquistaxi1"] = distributionTable["CarTaxi"]
distributionTable["92grandmarquistaxi2"] = distributionTable["CarTaxi"]
distributionTable["93sevillests"] = distributionTable["CarNormal"]
distributionTable["92intrepid"] = distributionTable["CarNormal"]
distributionTable["92intrepidtaxi"] = distributionTable["CarTaxi"]
distributionTable["92towncar"] = distributionTable["CarNormal"]
distributionTable["92towncartaxi"] = distributionTable["CarTaxi"]
distributionTable["93grandamsedan"] = distributionTable["CarNormal"]
distributionTable["93elderado"] = distributionTable["CarNormal"]
distributionTable["93grandamcoupe"] = distributionTable["CarNormal"]
distributionTable["86capricetaxi1"] = distributionTable["CarTaxi"]
distributionTable["86capricetaxi2"] = distributionTable["CarTaxi"]
distributionTable["85lesabre"] = distributionTable["CarNormal"]
distributionTable["85lesabretaxi1"] = distributionTable["CarTaxi"]
distributionTable["85lesabretaxi2"] = distributionTable["CarTaxi"]
distributionTable["89fury"] = distributionTable["CarNormal"]
distributionTable["92deville"] = distributionTable["CarNormal"]
distributionTable["93fleetwood"] = distributionTable["CarNormal"]
distributionTable["92roadmaster"] = distributionTable["CarNormal"]
distributionTable["85delta88"] = distributionTable["CarNormal"]
distributionTable["85delta88taxi1"] = distributionTable["CarTaxi"]
distributionTable["85delta88taxi2"] = distributionTable["CarTaxi"]
distributionTable["92lesaber"] = distributionTable["CarNormal"]
distributionTable["85fifthavenue"] = distributionTable["CarNormal"]
distributionTable["85impala"] = distributionTable["CarNormal"]
distributionTable["85impalacruiser"] = distributionTable["CarNormal"]
distributionTable["85impalataxi"] = distributionTable["CarTaxi"]
distributionTable["85impalataxi1"] = distributionTable["CarTaxi"]
distributionTable["93fordthunderbird"] = distributionTable["CarNormal"]
distributionTable["93markviii"] = distributionTable["CarNormal"]
distributionTable["89cougar"] = distributionTable["CarNormal"]
distributionTable["88riviera"] = distributionTable["CarNormal"]
distributionTable["90bonnevillesse"] = distributionTable["CarNormal"]
distributionTable["92vision"] = distributionTable["CarNormal"]
distributionTable["93taurus"] = distributionTable["CarNormal"]
distributionTable["90regalsedan"] = distributionTable["CarNormal"]
distributionTable["88lebaron"] = distributionTable["CarNormal"]
distributionTable["90supreme"] = distributionTable["CarNormal"]
distributionTable["88lesabrecoupe"] = distributionTable["CarNormal"]
distributionTable["90laser"] = distributionTable["CarNormal"]
distributionTable["90tornado"] = distributionTable["CarNormal"]
distributionTable["90beretta"] = distributionTable["CarNormal"]
distributionTable["93lumiasedan"] = distributionTable["CarNormal"]
distributionTable["92bronco"] = distributionTable["CarNormal"]
distributionTable["92typhoon"] = distributionTable["CarNormal"]

distributionTable["77caprice"] = distributionTable["CarNormal"]
distributionTable["77capricetaxi1"] = distributionTable["CarTaxi"]
distributionTable["77capricetaxi2"] = distributionTable["CarTaxi"]
distributionTable["77delta88"] = distributionTable["CarNormal"]
distributionTable["77lesabre"] = distributionTable["CarNormal"]
distributionTable["78Diplomat"] = distributionTable["CarNormal"]
distributionTable["78Diplomattaxi1"] = distributionTable["CarTaxi"]
distributionTable["78Diplomattaxi2"] = distributionTable["CarTaxi"]
distributionTable["78LTD"] = distributionTable["CarNormal"]
distributionTable["78LTDlandau"] = distributionTable["CarNormal"]
distributionTable["81catalina"] = distributionTable["CarNormal"]
distributionTable["81stregis"] = distributionTable["CarNormal"]
distributionTable["81fury"] = distributionTable["CarNormal"]
distributionTable["81newport"] = distributionTable["CarNormal"]
distributionTable["81stregistaxi1"] = distributionTable["CarTaxi"]
distributionTable["81stregistaxi2"] = distributionTable["CarTaxi"]
distributionTable["82lebaron"] = distributionTable["CarNormal"]
distributionTable["82lebarontaxi1"] = distributionTable["CarTaxi"]
distributionTable["82lebarontaxi2"] = distributionTable["CarTaxi"]
distributionTable["80crownvictorialtd"] = distributionTable["CarNormal"]
distributionTable["84grandmarquis"] = distributionTable["CarNormal"]
distributionTable["84towncar"] = distributionTable["CarNormal"]
distributionTable["86crownvictoria"] = distributionTable["CarNormal"]
distributionTable["86crownvictorialtdtaxi1"] = distributionTable["CarTaxi"]
distributionTable["86crownvictorialtdtaxi2"] = distributionTable["CarTaxi"]
distributionTable["86parisienne"] = distributionTable["CarNormal"]
distributionTable["89grandmarquis"] = distributionTable["CarNormal"]
distributionTable["90supremesedan"] = distributionTable["CarNormal"]
distributionTable["92imperial"] = distributionTable["CarNormal"]
distributionTable["90century"] = distributionTable["CarNormal"]
distributionTable["90skylark"] = distributionTable["CarNormal"]
distributionTable["91spirit"] = distributionTable["CarNormal"]
distributionTable["91newyorker"] = distributionTable["CarNormal"]
distributionTable["90electra"] = distributionTable["CarNormal"]
distributionTable["90pontiac6000"] = distributionTable["CarNormal"]
distributionTable["91grandpresedan"] = distributionTable["CarNormal"]
distributionTable["90grandamsedan"] = distributionTable["CarNormal"]
distributionTable["90cutlessciera"] = distributionTable["CarNormal"]
distributionTable["90cutlasscalais"] = distributionTable["CarNormal"]
distributionTable["90ninetyeight"] = distributionTable["CarNormal"]
distributionTable["90sixtyspecial"] = distributionTable["CarNormal"]

-- \\\\\\\\\\\\\\\/////////////// --
--          SPECIAL VEHICLES      --
-- \\\\\\\\\\\\\\\/////////////// --

-- Sports Cars

distributionTable["93camaro"] = distributionTable["SportsCar"]
distributionTable["93transam"] = distributionTable["SportsCar"]
distributionTable["93dodgeviper"] = distributionTable["SportsCar"]
distributionTable["87fordthunderbird"] = distributionTable["SportsCar"]
distributionTable["93corvette"] = distributionTable["SportsCar"]
distributionTable["92grandprix"] = distributionTable["SportsCar"]
distributionTable["92lumiacoupe"] = distributionTable["SportsCar"]

-- Station Wagons

distributionTable["85impalawagon"] = distributionTable["CarStationWagon"]
distributionTable["86capricewagon"] = distributionTable["CarStationWagon"]
distributionTable["89LeSabreWagon"] = distributionTable["CarStationWagon"]
distributionTable["90capricewagon"] = distributionTable["CarStationWagon"]
distributionTable["90crownvictoriawagon"] = distributionTable["CarStationWagon"]
distributionTable["92Colonypark"] = distributionTable["CarStationWagon"]
distributionTable["92crownvictoriawagon"] = distributionTable["CarStationWagon"]
distributionTable["89Diplomatwagon"] = distributionTable["CarStationWagon"]

-- SUVs

distributionTable["93tahoe"] = distributionTable["SUV"]
distributionTable["93suburban"] = distributionTable["SUV"]
distributionTable["93yukon"] = distributionTable["SUV"]
distributionTable["93gmcsuburban"] = distributionTable["SUV"]
distributionTable["93blazer"] = distributionTable["SUV"]
distributionTable["93gmcblazer"] = distributionTable["SUV"]
distributionTable["92Jimmy"] = distributionTable["SUV"]
distributionTable["91chevysuburban"] = distributionTable["SUV"]

-- Pickup Trucks

distributionTable["92F150"] = distributionTable["PickUpTruck"]
distributionTable["92F150long"] = distributionTable["PickUpTruck"]
distributionTable["92syclone"] = distributionTable["PickUpTruck"]
distributionTable["92gmcserria"] = distributionTable["PickUpTruck"]
distributionTable["92gmcserriamedium"] = distributionTable["PickUpTruck"]
distributionTable["92gmcserriadualsmall"] = distributionTable["PickUpTruck"]
distributionTable["92gmcserriadual"] = distributionTable["PickUpTruck"]
distributionTable["92cyclone4x4"] = distributionTable["PickUpTruck"]
distributionTable["92F150duallong"] = distributionTable["PickUpTruck"]
distributionTable["92F150dual"] = distributionTable["PickUpTruck"]
distributionTable["92silvarado"] = distributionTable["PickUpTruck"]
distributionTable["92silvaradolong"] = distributionTable["PickUpTruck"]
distributionTable["92F1504x4"] = distributionTable["PickUpTruck"]
distributionTable["92silvarado4x4"] = distributionTable["PickUpTruck"]
distributionTable["92F150duallong4x4"] = distributionTable["PickUpTruck"]
distributionTable["92F1504x4"] = distributionTable["PickUpTruck"]

-- police

distributionTable["86caprice9c1police"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["90caprice9c1police"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["90crownvictorialtdpolice"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92crownvictoriap71police"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["93crownvictoriap71police"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["919c1police"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["939c1police"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["89diplomatpolice"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["85lesabrepolice"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["89furypolice"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["85delta88police"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["939c1policecruiser"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["939c1policecruiser2"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["93capricestatepolice1"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["93capricestatepolice2"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["93FL70swat"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["87macktruckswat"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["93tahoepolice"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92intrepidpolice"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["93interceptorp71"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["93interceptor2p71"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92broncopolice"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["93yukonpolice"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["82lebaronpolice"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["86crownvictorialtdpolice"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["81stregispolice"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["88W900swat"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92grandmarquissheriff"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92F150sheriff"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92gmcserriasheriff"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["92intrepidstatepolice"] = distributionTable["PickUpVanLightsPolice"]
distributionTable["93crownvictoriap71state"] = distributionTable["PickUpVanLightsPolice"]

-- Fire Department

distributionTable["93capricewagonfire"] = distributionTable["PickUpTruckLightsFire"]
distributionTable["939c1fire"] = distributionTable["PickUpTruckLightsFire"]
distributionTable["93lefrance"] = distributionTable["PickUpTruckLightsFire"]
distributionTable["93lefrance2"] = distributionTable["PickUpTruckLightsFire"]
distributionTable["88w900firedept"] = distributionTable["PickUpTruckLightsFire"]
distributionTable["92gmcserriafiredept"] = distributionTable["PickUpTruckLightsFire"]
distributionTable["93frieghtlignerambulancefire"] = distributionTable["PickUpTruckLightsFire"]

-- Ambulances

distributionTable["93frieghtlignerambulance"] = distributionTable["VanAmbulance"]
distributionTable["93c10boxambulance"] = distributionTable["VanAmbulance"]
distributionTable["93c10vanambulance"] = distributionTable["VanAmbulance"]
distributionTable["87gmcc7000ambulance"] = distributionTable["VanAmbulance"]

-- Vans

distributionTable["93G10van"] = distributionTable["Van"]
distributionTable["93vandura"] = distributionTable["Van"]
distributionTable["93c10vanshort"] = distributionTable["Van"]
distributionTable["93vandurashort"] = distributionTable["Van"]
distributionTable["93vanduraspiffo"] = distributionTable["VanSpiffo"]
distributionTable["93vandurashortspiffo"] = distributionTable["VanSpiffo"]
distributionTable["93G10vanlectromax"] = distributionTable["Van_Transit"]
distributionTable["93c10vanshortlectromax"] = distributionTable["Van_Transit"]
distributionTable["Base.93vanduramassgenfacvo"] = distributionTable["Van_MassGenFac"]
distributionTable["Base.93G10massgenfacvo"] = distributionTable["Van_MassGenFac"]
distributionTable["Base.93G10KnoxDisti"] = distributionTable["Van_KnoxDisti"]
distributionTable["Base.93vanduraKnoxDisti"] = distributionTable["Van_KnoxDisti"]
distributionTable["Base.93vanduraScarlet"] = distributionTable["StepVan_Scarlet"]
distributionTable["Base.93G10Scarlet"] = distributionTable["StepVan_Scarlet"]
distributionTable["Base.93G10fossoil"] = distributionTable["PickUpVanLights1"]
distributionTable["Base.93vandurafossoil"] = distributionTable["PickUpVanLights1"]

-- Trucks

distributionTable["93fl70box"] = distributionTable["StepVan"]
distributionTable["87macktruckbox"] = distributionTable["StepVan"]
distributionTable["88w900fossoil"] = distributionTable["PickUpTruckLights1"]
distributionTable["88w900scarletdist"] = distributionTable["StepVan_Scarlet"]
distributionTable["88w900massgenfacvo"] = distributionTable["Van_MassGenFac"]
distributionTable["93fl70flatbed"] = distributionTable["StepVan"]
distributionTable["87macktrucklflatbed"] = distributionTable["StepVan"]
distributionTable["88navistarbox"] = distributionTable["StepVan"]
distributionTable["88navistarboxknoxdistillery"] = distributionTable["Van_KnoxDisti"]
distributionTable["88navistarboxmail"] = distributionTable["VanSpecial2"]
distributionTable["88navistarboxspiffo"] = distributionTable["VanSpiffo"]
distributionTable["87gmcarmouredcar"] = distributionTable["StepVan"]
distributionTable["88w900"] = distributionTable["StepVan"]

-- McCoy Vehicles

distributionTable["93fl70logcarrier"] = distributionTable["PickUpVanMccoy"]
distributionTable["93fl70logcarrier2"] = distributionTable["PickUpVanMccoy"]
distributionTable["87macktrucklogcarrier"] = distributionTable["PickUpVanMccoy"]
distributionTable["87macktrucklogcarrier2"] = distributionTable["PickUpVanMccoy"]
distributionTable["88navistarlogging1"] = distributionTable["PickUpVanMccoy"]
distributionTable["88navistarlogging2"] = distributionTable["PickUpVanMccoy"]
distributionTable["88w900logcarrier1"] = distributionTable["PickUpVanMccoy"]
distributionTable["88w900logcarrier2"] = distributionTable["PickUpVanMccoy"]


-- Bueses

distributionTable["87rtsbus"] = distributionTable["StepVan"]
distributionTable["87rtsbusshort"] = distributionTable["StepVan"]