require 'Items/ProceduralDistributions'

table.insert(ProceduralDistributions.list["ArmyHangarOutfit"].items, "Hat_CrashHelmet_Police")
table.insert(ProceduralDistributions.list["ArmyHangarOutfit"].items, 0.5)
table.insert(ProceduralDistributions.list["FireStorageOutfit"].items, "Hat_CrashHelmetFULL")
table.insert(ProceduralDistributions.list["FireStorageOutfit"].items, 0.5)
table.insert(ProceduralDistributions.list["FireStorageOutfit"].items, "Hat_CrashHelmet")
table.insert(ProceduralDistributions.list["FireStorageOutfit"].items, 0.5)
table.insert(ProceduralDistributions.list["ArmyHangarOutfit"].items, "Hat_CrashHelmet_Stars")
table.insert(ProceduralDistributions.list["ArmyHangarOutfit"].items, 0.5)

table.insert(ProceduralDistributions.list["MechanicShelfOutfit"].items, "Hat_CrashHelmet_Police")
table.insert(ProceduralDistributions.list["MechanicShelfOutfit"].items, 0.5)
table.insert(ProceduralDistributions.list["MechanicShelfOutfit"].items, "Hat_CrashHelmetFULL")
table.insert(ProceduralDistributions.list["MechanicShelfOutfit"].items, 0.5)
table.insert(ProceduralDistributions.list["MechanicShelfOutfit"].items, "Hat_CrashHelmet")
table.insert(ProceduralDistributions.list["MechanicShelfOutfit"].items, 0.5)
table.insert(ProceduralDistributions.list["MechanicShelfOutfit"].items, "Hat_CrashHelmet_Stars")
table.insert(ProceduralDistributions.list["MechanicShelfOutfit"].items, 0.5)

table.insert(ProceduralDistributions.list["PoliceStorageOutfit"].items, "Hat_CrashHelmet_Police")
table.insert(ProceduralDistributions.list["PoliceStorageOutfit"].items, 0.5)
table.insert(ProceduralDistributions.list["PoliceStorageOutfit"].items, "Hat_CrashHelmetFULL")
table.insert(ProceduralDistributions.list["PoliceStorageOutfit"].items, 0.5)
table.insert(ProceduralDistributions.list["PoliceStorageOutfit"].items, "Hat_CrashHelmet")
table.insert(ProceduralDistributions.list["PoliceStorageOutfit"].items, 0.5)
table.insert(ProceduralDistributions.list["PoliceStorageOutfit"].items, "Hat_CrashHelmet_Stars")
table.insert(ProceduralDistributions.list["PoliceStorageOutfit"].items, 0.5)


table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "Hat_CrashHelmet_Police")
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.02)
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "Hat_CrashHelmetFULL")
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.02)
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "Hat_CrashHelmet")
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.02)
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "Hat_CrashHelmet_Stars")
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.02)

table.insert(ProceduralDistributions.list["CrateSports"].items, "Hat_CrashHelmet_Police")
table.insert(ProceduralDistributions.list["CrateSports"].items, 0.02)
table.insert(ProceduralDistributions.list["CrateSports"].items, "Hat_CrashHelmetFULL")
table.insert(ProceduralDistributions.list["CrateSports"].items, 0.02)
table.insert(ProceduralDistributions.list["CrateSports"].items, "Hat_CrashHelmet")
table.insert(ProceduralDistributions.list["CrateSports"].items, 0.02)
table.insert(ProceduralDistributions.list["CrateSports"].items, "Hat_CrashHelmet_Stars")
table.insert(ProceduralDistributions.list["CrateSports"].items, 0.02)

table.insert(ProceduralDistributions.list["WardrobeMan"].items, "Hat_CrashHelmet_Police")
table.insert(ProceduralDistributions.list["WardrobeMan"].items, 0.5)
table.insert(ProceduralDistributions.list["WardrobeMan"].items, "Hat_CrashHelmetFULL")
table.insert(ProceduralDistributions.list["WardrobeMan"].items, 0.5)
table.insert(ProceduralDistributions.list["WardrobeMan"].items, "Hat_CrashHelmet")
table.insert(ProceduralDistributions.list["WardrobeMan"].items, 0.5)
table.insert(ProceduralDistributions.list["WardrobeMan"].items, "Hat_CrashHelmet_Stars")
table.insert(ProceduralDistributions.list["WardrobeMan"].items, 0.5)

table.insert(ProceduralDistributions.list["SportStorageHelmets"].items, "Hat_CrashHelmet_Police")
table.insert(ProceduralDistributions.list["SportStorageHelmets"].items, 0.5)
table.insert(ProceduralDistributions.list["SportStorageHelmets"].items, "Hat_CrashHelmetFULL")
table.insert(ProceduralDistributions.list["SportStorageHelmets"].items, 0.5)
table.insert(ProceduralDistributions.list["SportStorageHelmets"].items, "Hat_CrashHelmet")
table.insert(ProceduralDistributions.list["SportStorageHelmets"].items, 0.5)
table.insert(ProceduralDistributions.list["SportStorageHelmets"].items, "Hat_CrashHelmet_Stars")
table.insert(ProceduralDistributions.list["SportStorageHelmets"].items, 0.5)

table.insert(VehicleDistributions.SurvivalistTruckBed.items, "Hat_CrashHelmet_Police")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.5)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "Hat_CrashHelmetFULL")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.5)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "Hat_CrashHelmet")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.5)
table.insert(VehicleDistributions.SurvivalistTruckBed.items, "Hat_CrashHelmet_Stars")
table.insert(VehicleDistributions.SurvivalistTruckBed.items, 0.5)
