require 'Items/ProceduralDistributions'
require 'Items/SuburbsDistributions'

table.insert(ProceduralDistributions.list["SchoolLockers"].items, "pkmncards.boosterpack");
table.insert(ProceduralDistributions.list["SchoolLockers"].items, 5);
table.insert(ProceduralDistributions.list["SchoolLockers"].items, "pkmncards.boosterpackjungle");
table.insert(ProceduralDistributions.list["SchoolLockers"].items, 5);
table.insert(ProceduralDistributions.list["SchoolLockers"].items, "pkmncards.boosterpackfossil");
table.insert(ProceduralDistributions.list["SchoolLockers"].items, 5);
table.insert(ProceduralDistributions.list["SchoolLockers"].items, "pkmncards.pkmncollectiontin");
table.insert(ProceduralDistributions.list["SchoolLockers"].items, 0.5);
table.insert(ProceduralDistributions.list["GigamartToys"].items, "pkmncards.boosterpack");
table.insert(ProceduralDistributions.list["GigamartToys"].items, 5);
table.insert(ProceduralDistributions.list["GigamartToys"].items, "pkmncards.boosterpackjungle");
table.insert(ProceduralDistributions.list["GigamartToys"].items, 5);
table.insert(ProceduralDistributions.list["GigamartToys"].items, "pkmncards.boosterpackfossil");
table.insert(ProceduralDistributions.list["GigamartToys"].items, 5);
table.insert(ProceduralDistributions.list["GigamartToys"].items, "pkmncards.boosterbox");
table.insert(ProceduralDistributions.list["GigamartToys"].items, 0.5);
table.insert(ProceduralDistributions.list["GigamartToys"].items, "pkmncards.boosterboxjungle");
table.insert(ProceduralDistributions.list["GigamartToys"].items, 0.5);
table.insert(ProceduralDistributions.list["GigamartToys"].items, "pkmncards.boosterboxfossil");
table.insert(ProceduralDistributions.list["GigamartToys"].items, 0.5);
table.insert(ProceduralDistributions.list["GigamartToys"].items, "pkmncards.cardbinder_empty");
table.insert(ProceduralDistributions.list["GigamartToys"].items, 1.2);
table.insert(ProceduralDistributions.list["GigamartToys"].items, "pkmncards.pkmn_checklist");
table.insert(ProceduralDistributions.list["GigamartToys"].items, 1.5);
table.insert(ProceduralDistributions.list["GigamartToys"].items, "pkmncards.pkmncollectiontin");
table.insert(ProceduralDistributions.list["GigamartToys"].items, 1.5);
table.insert(ProceduralDistributions.list["CrateToys"].items, "pkmncards.boosterpack");
table.insert(ProceduralDistributions.list["CrateToys"].items, 3);
table.insert(ProceduralDistributions.list["CrateToys"].items, "pkmncards.boosterpackjungle");
table.insert(ProceduralDistributions.list["CrateToys"].items, 3);
table.insert(ProceduralDistributions.list["CrateToys"].items, "pkmncards.boosterpackfossil");
table.insert(ProceduralDistributions.list["CrateToys"].items, 3);
table.insert(ProceduralDistributions.list["CrateToys"].items, "pkmncards.boosterbox");
table.insert(ProceduralDistributions.list["CrateToys"].items, 1.0);
table.insert(ProceduralDistributions.list["CrateToys"].items, "pkmncards.boosterboxjungle");
table.insert(ProceduralDistributions.list["CrateToys"].items, 1.0);
table.insert(ProceduralDistributions.list["CrateToys"].items, "pkmncards.boosterboxfossil");
table.insert(ProceduralDistributions.list["CrateToys"].items, 1.0);
table.insert(ProceduralDistributions.list["CrateToys"].items, "pkmncards.cardbinder_empty");
table.insert(ProceduralDistributions.list["CrateToys"].items, 1.3);
table.insert(ProceduralDistributions.list["CrateToys"].items, "pkmncards.pkmn_checklist");
table.insert(ProceduralDistributions.list["CrateToys"].items, 2.0);
table.insert(ProceduralDistributions.list["CrateToys"].items, "pkmncards.pkmncollectiontin");
table.insert(ProceduralDistributions.list["CrateToys"].items, 2.0);
table.insert(ProceduralDistributions.list["WardrobeChild"].items, "pkmncards.boosterpack");
table.insert(ProceduralDistributions.list["WardrobeChild"].items, 4);
table.insert(ProceduralDistributions.list["WardrobeChild"].items, "pkmncards.boosterpackjungle");
table.insert(ProceduralDistributions.list["WardrobeChild"].items, 4);
table.insert(ProceduralDistributions.list["WardrobeChild"].items, "pkmncards.boosterpackfossil");
table.insert(ProceduralDistributions.list["WardrobeChild"].items, 4);
table.insert(ProceduralDistributions.list["WardrobeChild"].items, "pkmncards.cardbinder_empty");
table.insert(ProceduralDistributions.list["WardrobeChild"].items, 2);
table.insert(ProceduralDistributions.list["WardrobeChild"].items, "pkmncards.pkmn_checklist");
table.insert(ProceduralDistributions.list["WardrobeChild"].items, 3);
table.insert(ProceduralDistributions.list["WardrobeChild"].items, "pkmncards.pkmncollectiontin");
table.insert(ProceduralDistributions.list["WardrobeChild"].items, 2);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "pkmncards.boosterpack");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 5);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "pkmncards.boosterpackjungle");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 5);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "pkmncards.boosterpackfossil");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 5);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "pkmncards.cardbinder_empty");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 3);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "pkmncards.pkmn_checklist");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 2);
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, "pkmncards.boosterpack");
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, 3);
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, "pkmncards.boosterpackJungle");
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, 3);
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, "pkmncards.boosterpackfossil");
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, 3);
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, "pkmncards.pkmncollectiontin");
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, 0.3);
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "pkmncards.boosterpack");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.7);
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "pkmncards.boosterpackJungle");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.7);
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "pkmncards.boosterpackfossil");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.7);
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "pkmncards.boosterbox");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "pkmncards.boosterboxjungle");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "pkmncards.boosterboxfossil");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "pkmncards.pkmncollectiontin");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.1);
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "pkmncards.boosterpack");
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.7);
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "pkmncards.boosterpackJungle");
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.7);
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "pkmncards.boosterpackfossil");
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.7);
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "pkmncards.pkmncollectiontin");
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.4);
table.insert(ProceduralDistributions.list["RandomFiller"].items, "pkmncards.boosterpack");
table.insert(ProceduralDistributions.list["RandomFiller"].items, 0.1);
table.insert(ProceduralDistributions.list["RandomFiller"].items, "pkmncards.boosterpackJungle");
table.insert(ProceduralDistributions.list["RandomFiller"].items, 0.1);
table.insert(ProceduralDistributions.list["RandomFiller"].items, "pkmncards.boosterpackfossil");
table.insert(ProceduralDistributions.list["RandomFiller"].items, 0.1);
table.insert(SuburbsDistributions.all.inventorymale.items, "pkmncards.boosterpack")
table.insert(SuburbsDistributions.all.inventorymale.items, 2.7)
table.insert(SuburbsDistributions.all.inventorymale.items, "pkmncards.boosterpackjungle")
table.insert(SuburbsDistributions.all.inventorymale.items, 2.7)
table.insert(SuburbsDistributions.all.inventorymale.items, "pkmncards.boosterpackfossil")
table.insert(SuburbsDistributions.all.inventorymale.items, 2.7)
table.insert(SuburbsDistributions.all.inventoryfemale.items, "pkmncards.boosterpack")
table.insert(SuburbsDistributions.all.inventoryfemale.items, 2.7)
table.insert(SuburbsDistributions.all.inventoryfemale.items, "pkmncards.boosterpackjungle")
table.insert(SuburbsDistributions.all.inventoryfemale.items, 2.7)
table.insert(SuburbsDistributions.all.inventoryfemale.items, "pkmncards.boosterpackfossil")
table.insert(SuburbsDistributions.all.inventoryfemale.items, 2.7)