--
-- Created by IntelliJ IDEA.
-- User: RJ
-- Date: 06/02/14
-- Time: 10:22
-- To change this template use File | Settings | File Templates.
--
---MODIFIED BY UNGRATEFULDEAD---
-- Traps definition
Traps = {};
local crateTrap = {};
crateTrap.type = "Base.TrapCrate";
crateTrap.sprite = "constructedobjects_01_3";
crateTrap.closedSprite = "constructedobjects_01_2";
crateTrap.trapStrength = 15;
table.insert(Traps, crateTrap);
local trapBox = {};
trapBox.type = "Base.TrapBox";
trapBox.sprite = "constructedobjects_01_4";
trapBox.northSprite = "constructedobjects_01_7";
trapBox.closedSprite = "constructedobjects_01_5";
trapBox.northClosedSprite = "constructedobjects_01_6";
trapBox.trapStrength = 15;
table.insert(Traps, trapBox);
local cageTrap = {};
cageTrap.type = "Base.TrapCage";
cageTrap.sprite = "constructedobjects_01_8";
cageTrap.northSprite = "constructedobjects_01_11";
cageTrap.closedSprite = "constructedobjects_01_9";
cageTrap.northClosedSprite = "constructedobjects_01_10";
cageTrap.trapStrength = 20;
table.insert(Traps, cageTrap);
local snareTrap = {};
snareTrap.type = "Base.TrapSnare";
snareTrap.sprite = "constructedobjects_01_16";
snareTrap.closedSprite = "constructedobjects_01_17";
snareTrap.trapStrength = 10;
table.insert(Traps, snareTrap);
local stickTrap = {};
stickTrap.type = "Base.TrapStick";
stickTrap.sprite = "constructedobjects_01_13";
stickTrap.closedSprite = "constructedobjects_01_13";
stickTrap.trapStrength = 15;
table.insert(Traps, stickTrap);
local mouseTrap = {};
mouseTrap.type = "Base.TrapMouse";
mouseTrap.sprite = "constructedobjects_01_18";
mouseTrap.closedSprite = "constructedobjects_01_19";
mouseTrap.trapStrength = 50;
table.insert(Traps, mouseTrap);

-- Animals definition
Animals = {};
local rabbit = {};
rabbit.type = "rabbit";
-- after how many hour the animal will start to destroy the cage/escape
rabbit.strength = 24;
-- item given to the player
rabbit.item = "HuntingMod.HMDeadRabbit";
-- hour this animal will be out and when you can catch it
rabbit.minHour = 19;
rabbit.maxHour = 5;
-- min and max "size" (understand hunger reduction) of the animal
rabbit.minSize = 15;
rabbit.maxSize = 60;
-- chance to get the animals per zone
rabbit.zone = {};
rabbit.zone["TownZone"] = 2;
rabbit.zone["TrailerPark"] = 2;
rabbit.zone["Vegitation"] = 10;
rabbit.zone["Forest"] = 12;
rabbit.zone["DeepForest"] = 15;
-- chance to get animals for each trap
rabbit.traps = {};
rabbit.traps["Base.TrapCage"] = 30;
rabbit.traps["Base.TrapSnare"] = 20;
rabbit.traps["Base.TrapBox"] = 20;
rabbit.traps["Base.TrapCrate"] = 20;
-- chance to attract animal per bait
rabbit.baits = {};
rabbit.baits["Base.Carrots"] = 25;
rabbit.baits["Base.Apple"] = 15;
rabbit.baits["Base.Lettuce"] = 20;
rabbit.baits["Base.BellPepper"] = 20;
rabbit.baits["farming.Cabbage"] = 20;
rabbit.baits["Base.Corn"] = 15;
rabbit.baits["Base.Banana"] = 15;
rabbit.baits["farming.Potato"] = 15;
rabbit.baits["farming.Tomato"] = 15;
rabbit.baits["Base.Peach"] = 15;

local squirrel = {};
squirrel.type = "squirrel";
squirrel.strength = 20;
squirrel.item = "HuntingMod.HMDeadSquirrel";
squirrel.minHour = 19;
squirrel.maxHour = 5;
squirrel.minSize = 10;
squirrel.maxSize = 30;
squirrel.zone = {};
squirrel.zone["TownZone"] = 2;
squirrel.zone["TrailerPark"] = 2;
squirrel.zone["Vegitation"] = 10;
squirrel.zone["Forest"] = 12;
squirrel.zone["DeepForest"] = 15;
squirrel.traps = {};
squirrel.traps["Base.TrapBox"] = 15;
squirrel.traps["Base.TrapCage"] = 30;
squirrel.traps["Base.TrapCrate"] = 20;
squirrel.traps["Base.TrapSnare"] = 20;
squirrel.baits = {};
squirrel.baits["Base.PeanutButter"] = 25;
squirrel.baits["Base.Cereal"] = 25;
squirrel.baits["Base.Orange"] = 20;
squirrel.baits["Base.Peanuts"] = 20;
squirrel.baits["Base.Apple"] = 20;
squirrel.baits["Base.Corn"] = 20;
squirrel.baits["Base.Popcorn"] = 20;
squirrel.baits["Base.Lettuce"] = 20;
squirrel.baits["Base.BellPepper"] = 10;
squirrel.baits["Base.Peach"] = 15;

local raccoon = {};
raccoon.type = "raccoon";
raccoon.strength = 26;
raccoon.item = "HuntingMod.HMDeadRaccoon";
raccoon.minHour = 19;
raccoon.maxHour = 5;
raccoon.minSize = 15;
raccoon.maxSize = 40;
raccoon.zone = {};
raccoon.zone["TownZone"] = 30;
raccoon.zone["TrailerPark"] = 30;
raccoon.zone["Vegitation"] = 12;
raccoon.zone["Forest"] = 12;
raccoon.zone["DeepForest"] = 8;
raccoon.traps = {};
raccoon.traps["Base.TrapBox"] = 15;
raccoon.traps["Base.TrapCage"] = 30;
raccoon.traps["Base.TrapCrate"] = 20;
raccoon.traps["Base.TrapSnare"] = 20;
raccoon.baits = {};
raccoon.baits["Base.PeanutButter"] = 25;
raccoon.baits["Base.Cereal"] = 25;
raccoon.baits["Base.Orange"] = 20;
raccoon.baits["Base.Peanuts"] = 20;
raccoon.baits["Base.Apple"] = 20;
raccoon.baits["Base.Corn"] = 20;
raccoon.baits["Base.Popcorn"] = 20;
raccoon.baits["Base.Lettuce"] = 20;
raccoon.baits["Base.BellPepper"] = 10;
raccoon.baits["Base.Peach"] = 15;
raccoon.baits["Base.Cheese"] = 40;
raccoon.baits["farming.BaconBits"] = 20;
raccoon.baits["Base.Chocolate"] = 10;
raccoon.baits["farming.Tomato"] = 15;
raccoon.baits["Base.Processedcheese"] = 35;

local skunk = {};
skunk.type = "skunk";
skunk.strength = 22;
skunk.item = "HuntingMod.HMDeadSkunk";
skunk.minHour = 19;
skunk.maxHour = 5;
skunk.minSize = 10;
skunk.maxSize = 30;
skunk.zone = {};
skunk.zone["TownZone"] = 25;
skunk.zone["TrailerPark"] = 25;
skunk.zone["Vegitation"] = 10;
skunk.zone["Forest"] = 10;
skunk.zone["DeepForest"] = 10;
skunk.traps = {};
skunk.traps["Base.TrapBox"] = 15;
skunk.traps["Base.TrapCage"] = 30;
skunk.traps["Base.TrapCrate"] = 20;
skunk.traps["Base.TrapSnare"] = 20;
skunk.baits = {};
skunk.baits["Base.PeanutButter"] = 25;
skunk.baits["Base.Cereal"] = 25;
skunk.baits["Base.Orange"] = 20;
skunk.baits["Base.Peanuts"] = 20;
skunk.baits["Base.Apple"] = 20;
skunk.baits["Base.Corn"] = 20;
skunk.baits["Base.Popcorn"] = 20;
skunk.baits["Base.Lettuce"] = 20;
skunk.baits["Base.BellPepper"] = 10;
skunk.baits["Base.Peach"] = 15;
skunk.baits["Base.Cheese"] = 40;
skunk.baits["farming.BaconBits"] = 20;
skunk.baits["Base.Chocolate"] = 10;
skunk.baits["farming.Tomato"] = 15;
skunk.baits["Base.Processedcheese"] = 35;

local opossum = {};
opossum.type = "opossum";
opossum.strength = 22;
opossum.item = "HuntingMod.HMDeadOpossum";
opossum.minHour = 19;
opossum.maxHour = 5;
opossum.minSize = 12;
opossum.maxSize = 35;
opossum.zone = {};
opossum.zone["TownZone"] = 30;
opossum.zone["TrailerPark"] = 30;
opossum.zone["Vegitation"] = 12;
opossum.zone["Forest"] = 12;
opossum.zone["DeepForest"] = 8;
opossum.traps = {};
opossum.traps["Base.TrapBox"] = 15;
opossum.traps["Base.TrapCage"] = 30;
opossum.traps["Base.TrapCrate"] = 20;
opossum.traps["Base.TrapSnare"] = 20;
opossum.baits = {};
opossum.baits["Base.PeanutButter"] = 25;
opossum.baits["Base.Cereal"] = 25;
opossum.baits["Base.Orange"] = 20;
opossum.baits["Base.Peanuts"] = 20;
opossum.baits["Base.Apple"] = 20;
opossum.baits["Base.Corn"] = 20;
opossum.baits["Base.Popcorn"] = 20;
opossum.baits["Base.Lettuce"] = 20;
opossum.baits["Base.BellPepper"] = 10;
opossum.baits["Base.Peach"] = 15;
opossum.baits["Base.Cheese"] = 40;
opossum.baits["farming.BaconBits"] = 20;
opossum.baits["Base.Chocolate"] = 10;
opossum.baits["farming.Tomato"] = 15;
opossum.baits["Base.Processedcheese"] = 35;

local fox = {};
fox.type = "fox";
fox.strength = 23;
fox.item = "HuntingMod.HMDeadFox";
fox.minHour = 19;
fox.maxHour = 5;
fox.minSize = 20;
fox.maxSize = 42;
fox.zone = {};
fox.zone["TownZone"] = 5;
fox.zone["TrailerPark"] = 5;
fox.zone["Vegitation"] = 15;
fox.zone["Forest"] = 15;
fox.zone["DeepForest"] = 15;
fox.traps = {};
fox.traps["Base.TrapBox"] = 15;
fox.traps["Base.TrapCage"] = 30;
fox.traps["Base.TrapCrate"] = 20;
fox.traps["Base.TrapSnare"] = 20;
fox.baits = {};
fox.baits["Base.PeanutButter"] = 25;
fox.baits["Base.Cereal"] = 25;
fox.baits["Base.Orange"] = 20;
fox.baits["Base.Peanuts"] = 20;
fox.baits["Base.Apple"] = 20;
fox.baits["Base.Corn"] = 20;
fox.baits["Base.Popcorn"] = 20;
fox.baits["Base.Lettuce"] = 20;
fox.baits["Base.BellPepper"] = 10;
fox.baits["Base.Peach"] = 15;
fox.baits["Base.Cheese"] = 40;
fox.baits["farming.BaconBits"] = 20;
fox.baits["Base.Chocolate"] = 10;
fox.baits["farming.Tomato"] = 15;
fox.baits["Base.Processedcheese"] = 35;

local beaver = {};
beaver.type = "beaver";
beaver.strength = 30;
beaver.item = "HuntingMod.HMDeadBeaver";
beaver.minHour = 19;
beaver.maxHour = 5;
beaver.minSize = 40;
beaver.maxSize = 75;
beaver.zone = {};
beaver.zone["Vegitation"] = 15;
beaver.zone["Forest"] = 15;
beaver.zone["DeepForest"] = 20;
beaver.traps = {};
beaver.traps["Base.TrapBox"] = 15;
beaver.traps["Base.TrapCage"] = 30;
beaver.traps["Base.TrapCrate"] = 20;
beaver.baits = {};
beaver.baits["Base.PeanutButter"] = 25;
beaver.baits["Base.Cereal"] = 25;
beaver.baits["Base.Orange"] = 20;
beaver.baits["Base.Peanuts"] = 20;
beaver.baits["Base.Apple"] = 20;
beaver.baits["Base.Corn"] = 20;
beaver.baits["Base.Popcorn"] = 20;
beaver.baits["Base.Lettuce"] = 20;
beaver.baits["Base.BellPepper"] = 10;
beaver.baits["Base.Peach"] = 15;

local bird = {};
bird.type = "bird";
bird.item = "HuntingMod.HMDeadPigeon";
bird.minHour = 0;
bird.maxHour = 0;
bird.minSize = 6;
bird.maxSize = 14;
bird.zone = {};
bird.zone["FarmLand"] = 35;
bird.zone["TownZone"] = 30;
bird.zone["Vegitation"] = 30;
bird.zone["TrailerPark"] = 20;
bird.zone["Forest"] = 20;
bird.zone["DeepForest"] = 20;
bird.traps = {};
bird.traps["Base.TrapStick"] = 30;
bird.baits = {};
bird.baits["Base.Bread"] = 30;
bird.baits["Base.BreadSlices"] = 30;
bird.baits["Base.Worm"] = 30;
bird.baits["Base.Corn"] = 25;
bird.baits["Base.Cereal"] = 25;

local quail = {};
quail.type = "quail";
quail.strength = 5;
quail.item = "HuntingMod.HMDeadQuail";
quail.minHour = 0;
quail.maxHour = 0;
quail.minSize = 10;
quail.maxSize = 18;
quail.zone = {};
quail.zone["FarmLand"] = 35;
quail.zone["Vegitation"] = 30;
quail.zone["Forest"] = 20;
quail.zone["DeepForest"] = 20;
quail.traps = {};
quail.traps["Base.TrapStick"] = 30;
quail.baits = {};
quail.baits["Base.Bread"] = 30;
quail.baits["Base.BreadSlices"] = 30;
quail.baits["Base.Worm"] = 30;
quail.baits["Base.Corn"] = 25;
quail.baits["Base.Cereal"] = 25;

local duck = {};
duck.type = "duck";
duck.strength = 10;
duck.item = "HuntingMod.HMDeadDuck";
duck.minHour = 0;
duck.maxHour = 0;
duck.minSize = 15;
duck.maxSize = 25;
duck.zone = {};
duck.zone["FarmLand"] = 35;
duck.zone["Vegitation"] = 30;
duck.zone["Forest"] = 20;
duck.zone["DeepForest"] = 20;
duck.traps = {};
duck.traps["Base.TrapStick"] = 30;
duck.baits = {};
duck.baits["Base.Bread"] = 30;
duck.baits["Base.BreadSlices"] = 30;
duck.baits["Base.Worm"] = 30;
duck.baits["Base.Corn"] = 25;
duck.baits["Base.Cereal"] = 25;

local goose = {};
goose.type = "goose";
goose.strength = 20;
goose.item = "HuntingMod.HMDeadGoose";
goose.minHour = 0;
goose.maxHour = 0;
goose.minSize = 25;
goose.maxSize = 35;
goose.zone = {};
goose.zone["FarmLand"] = 35;
goose.zone["Vegitation"] = 30;
goose.zone["Forest"] = 20;
goose.zone["DeepForest"] = 20;
goose.traps = {};
goose.traps["Base.TrapStick"] = 30;
goose.baits = {};
goose.baits["Base.Bread"] = 30;
goose.baits["Base.BreadSlices"] = 30;
goose.baits["Base.Worm"] = 30;
goose.baits["Base.Corn"] = 25;
goose.baits["Base.Cereal"] = 25;

local turkey = {};
turkey.type = "turkey";
turkey.strength = 15;
turkey.item = "HuntingMod.HMDeadTurkey";
turkey.minHour = 0;
turkey.maxHour = 0;
turkey.minSize = 28;
turkey.maxSize = 35;
turkey.zone = {};
turkey.zone["FarmLand"] = 35;
turkey.zone["Vegitation"] = 30;
turkey.zone["Forest"] = 20;
turkey.zone["DeepForest"] = 20;
turkey.traps = {};
turkey.traps["Base.TrapStick"] = 30;
turkey.baits = {};
turkey.baits["Base.Bread"] = 30;
turkey.baits["Base.BreadSlices"] = 30;
turkey.baits["Base.Worm"] = 30;
turkey.baits["Base.Corn"] = 25;
turkey.baits["Base.Cereal"] = 25;

local mouse = {};
mouse.type = "mouse";
mouse.item = "Base.DeadMouse";
mouse.minHour = 0;
mouse.maxHour = 0;
mouse.minSize = 3;
mouse.maxSize = 13;
mouse.zone = {};
mouse.zone["FarmLand"] = 60;
mouse.zone["TownZone"] = 50;
mouse.zone["TrailerPark"] = 60;
mouse.zone["Vegitation"] = 20;
mouse.zone["Forest"] = 10;
mouse.zone["DeepForest"] = 10;
mouse.traps = {};
mouse.traps["Base.TrapMouse"] = 20;
mouse.baits = {};
mouse.baits["Base.Cheese"] = 40;
mouse.baits["Base.Processedcheese"] = 35;
mouse.baits["Base.PeanutButter"] = 20;
mouse.baits["farming.BaconBits"] = 20;
mouse.baits["Base.Chocolate"] = 10;
mouse.baits["Base.Orange"] = 15;
mouse.baits["farming.Apple"] = 15;
mouse.baits["farming.Tomato"] = 15;

local rat = {};
rat.type = "rat";
rat.item = "Base.DeadRat";
rat.minHour = 0;
rat.maxHour = 0;
rat.minSize = 6;
rat.maxSize = 17;
rat.zone = {};
rat.zone["FarmLand"] = 50;
rat.zone["TrailerPark"] = 40;
rat.zone["TownZone"] = 30;
rat.zone["Vegitation"] = 20;
rat.zone["Forest"] = 10;
rat.zone["DeepForest"] = 10;
rat.traps = {};
rat.traps["Base.TrapMouse"] = 15;
rat.baits = {};
rat.baits["Base.Cheese"] = 40;
rat.baits["Base.PeanutButter"] = 20;
rat.baits["farming.BaconBits"] = 20;
rat.baits["Base.Chocolate"] = 10;
rat.baits["Base.Orange"] = 15;
rat.baits["farming.Apple"] = 15;
rat.baits["farming.Tomato"] = 15;
rat.baits["Base.Processedcheese"] = 35;

table.insert(Animals, bird);
table.insert(Animals, rat);
table.insert(Animals, mouse);
table.insert(Animals, rabbit);
table.insert(Animals, squirrel);
table.insert(Animals, opossum);
table.insert(Animals, fox);
table.insert(Animals, raccoon);
table.insert(Animals, skunk);
table.insert(Animals, beaver);
table.insert(Animals, duck);
table.insert(Animals, quail);
table.insert(Animals, goose);
table.insert(Animals, turkey);