local GameAPI = require("ComputerMod/GameAPI");

GameAPI.Add("pz_b41", "Zombies Project", "1993", "The Indie Cobble", "Survival", "pz")
GameAPI.Add("metal_gear", "Metal Tear", "1987", "Tonami", "Stealth", "metal_gear")
GameAPI.Add("metal_gear_2", "Metal Tear 2: Solid Viper", "1990", "Tonami", "Stealth", "metal_gear_2")
GameAPI.Add("snake_revenge", "Vipers's Revenge", "1990", "Tonami", "Stealth", "snake_revenge")
GameAPI.Add("elite", "Exceed", "1984", "Horizon Development", "Space", "elite")
GameAPI.Add("donkey_kong", "King Kong", "1981", "Meyuso", "Arcade", "donkey_kong")
GameAPI.Add("contra", "Tontra", "1987", "Tonami", "Run & Gun", "Contra")
GameAPI.Add("the_legend_of_zelda", "The Legend of Gerwudo", "1986", "Meyuso", "Adventure", "the_legend_of_zelda")
GameAPI.Add("final_fantasy", "Initial Fantasy", "1986", "Circle", "RPG", "final_fantasy")
GameAPI.Add("the_lost_vikings", "The Lost Celts", "1992", "Froststorm Entertainment", "Arcade", "the_lost_vikings")
GameAPI.Add("tetris", "Tetris", "1984", "Alexey Pajitnov", "Puzzle", "tetris")
GameAPI.Add("duke_nukem", "Duke Gettum", "1991", "Epoch Software", "Platformer", "duke_nukem")
GameAPI.Add("doom", "Tomb", "1993", "Ego Software", "FPS", "doom")
GameAPI.Add("star_wars_x_wing", "Galaxee Wars: T-Wing", "1993", "ToucanArts", "Space", "star_wars_x_wing")
GameAPI.Add("lemmings", "Lemmings", "1991", "Psygnosis", "Puzzle", "lemmings")
GameAPI.Add("civilization", "Humans", "1991", "TinctureProse", "4X Strategy", "civilization")
GameAPI.Add("dune_2", "Dune II", "1992", "Virgin Games", "RTS", "dune_2")
GameAPI.Add("wolfenstein_3d", "Reichenbach 3D", "1992", "Epoch Software", "FPS", "wolfenstein")
GameAPI.Add("skate_or_die", "Skate or Jive!", "1987", "Computer Arts", "Sports", "skate_or_die")
GameAPI.Add("simcity", "Cities", "1989", "Axis", "Simulation", "simcity")
