--Read Your Manga
--https://steamcommunity.com/sharedfiles/filedetails/?id=2851584592
if getActivatedMods():contains("readym") then
GaistUtils.doParam("mangaItems.manga1","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga2","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga3","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga4","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga5","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga6","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga7","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga8","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga9","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga10","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga11","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga12","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga13","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga14","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga15","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga16","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga17","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga18","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga19","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga20","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga21","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga22","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga23","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga24","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga25","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga26","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga27","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga28","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga29","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga30","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga31","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga32","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga33","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga34","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga35","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga36","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga37","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga38","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga39","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga40","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga41","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga42","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga43","DisplayCategory","LitE");
GaistUtils.doParam("mangaItems.manga44","DisplayCategory","LitE");
end