local distributionTable = VehicleDistributions[1]

distributionTable["fhqHPGT40Police"] = distributionTable["CarLightsPolice"]
distributionTable["fhqHPR32GTRPolice"] = distributionTable["CarLightsPolice"]
distributionTable["fhqHPE36Police"] = distributionTable["CarLightsPolice"]
distributionTable["fhqHPLM002Ranger"] = distributionTable["CarLights0"]
distributionTable["fhqHPCappuccinoPE"] = distributionTable["CarLightsPolice"]
distributionTable["fhqHPSupraMkIVPoliceHP"] = distributionTable["CarLightsPolice"]
distributionTable["fhqHP300ZXZ32Police"] = distributionTable["CarLightsPolice"]
distributionTable["fhqHPChaserJZX90Police"] = distributionTable["CarLightsPolice"]
distributionTable["fhqHPStratosRallyRanger"] = distributionTable["CarLights0"]
distributionTable["fhqHPE36M3CoupePolice"] = distributionTable["CarLightsPolice"]
distributionTable["fhqHPFBMustangGTSheriff"] = distributionTable["CarLightsPolice"]
distributionTable["fhqHPE36M3GTRPolice"] = distributionTable["CarLightsPolice"]
distributionTable["fhqHPImprezaPolice"] = distributionTable["CarLightsPolice"]
distributionTable["fhqHPImprezaWRXWagRanger"] = distributionTable["CarLights0"]
distributionTable["fhqHPStratosPolice"] = distributionTable["CarLightsPolice"]